### ISSUE TITLE
Hey why you taking credit of NoHitDelayFixMod

### ISSUE THREAD

**Issue by ghost** [Moulberry/NoHitFix#1]
NoHitDelayFixMod was developed by ghast
Proof of evidence: https://github.com/ghast/HitDelayFixMod
You are a fake developer, exposed yourself

**Comment by Moulberry** [comment]
The original mod made a mistake which allowed you to click more than once per tick into the air, which was flagging some anticheats. I don't care either way since PVP is stupid
